CREATE SCHEMA IF NOT EXISTS taxi;

CREATE TABLE if not exists taxi.Trips (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    clientid text,
    driverid text,
    begin_route text,
    end_route text,
    trip_status integer
    )